version: 3

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

includes:
  template:
    dir: template
    taskfile: template/Taskfile.yml


tasks:
  default:
    cmd: task --list

  scaffold:
    desc: 'Scaffolds a new GitHub Action from the template | Usage: task scaffold -- my-action'
    silent: true
    cmds:
      - mkdir -p actions/{{ .CLI_ARGS }} && cp -r template/* actions/{{ .CLI_ARGS }}
      - sed -i '' 's#module github.com/thoughtgears/github-actions/template#module github.com/thoughtgears/github-actions/actions/{{ .CLI_ARGS }}#' actions/{{ .CLI_ARGS }}/go.mod
      - find actions/{{ .CLI_ARGS }} -name '*.go' -exec sed -i '' 's#github.com/thoughtgears/github-actions/template/generator#github.com/thoughtgears/github-actions/actions/{{ .CLI_ARGS }}/generator#g' {} +
      - sed -i '' 's/template/{{ .CLI_ARGS }}/' actions/{{ .CLI_ARGS }}/Taskfile.yml
      - rm -rf actions/{{ .CLI_ARGS }}/bin

