name: 'Thoughtgears GitHub Release'
description: 'Releases interesting things to GitHub'
author: 'Thoughtgears'

inputs:
  github_token:
    description: 'The GitHub token'
    required: true
  action:
    description: 'Name of the action to release'
    required: true
  latest:
    description: 'Set to true to create a latest release'
    default: 'true'
  prerelease:
    description: 'Set to true to create a prerelease'
    default: 'false'

runs:
  using: node20
  main: run.js
