name: Bundle and Release

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        actions: ['github-release']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Bundle action ${{ matrix.actions }}
        run: task ${{ matrixs.actions }} bundle

      - name: Release version
        if: github.ref == 'refs/tags/v*' # Only do releases on tags
        uses: ./actions/release
