name: Bundle and Release

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - template/** # Ignore changes to the template directory
      - .gitignore
      - .github/workflows/test.yml
      - .golangci.yml

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        actions: ['github-release']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: arduino/setup-task@v2

      - name: Bundle action ${{ matrix.actions }}
        run: task ${{ matrix.actions }} bundle

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push

# Set the body of the release to the commit message
# awk "/^## \[${VERSION_TAG}\]/ {flag=1; next} /^## / {flag=0} flag {print}" actions/github-release/CHANGELOG.md

      - name: Release version
        if: github.ref == 'refs/tags/v*' # Only do releases on tags
        uses: ./actions/release
