name: Bundle

on:
  push:
    branches:
      - main
    paths-ignore:
      - template/** # Ignore changes to the template directory
      - .gitignore
      - .github/workflows/test.yml
      - .github/workflows/release.yml
      - .golangci.yml

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        actions: ['github-release']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: arduino/setup-task@v2

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bundle action ${{ matrix.actions }}
        run: task ${{ matrix.actions }}:bundle

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
