name: Bundle and Release

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        actions: ['github-release']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Bundle action ${{ matrix.actions }}
        run: task ${{ matrix.actions }} bundle

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push

      - name: Release version
        if: github.ref == 'refs/tags/v*' # Only do releases on tags
        uses: ./actions/release
