name: Release

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
    - template/** # Ignore changes to the template directory
    - .gitignore
    - .github/workflows/test.yml
    - .github/workflows/bundle.yml
    - .golangci.yml


jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        actions: [ 'github-release' ]

    steps:
      - uses: actions/checkout@v4
      - name: Release ${{ matrix.actions }}
        uses: ./actions/github-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          action: ${{ matrix.actions }}

