name: Release

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  actions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        actions: ['github-release']

    outputs:
      filtered_actions: ${{ steps.filter-actions.outputs.filtered_actions }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter actions by version tag
        id: filter-actions
        run: |
          VERSION_TAG="echo ${{ github.ref }} | awk -F '/' '{print $NF}'"
          FILTERED_ACTIONS=""
          for action in ${{ matrix.actions }}
          do
            if grep -q "^## \[${VERSION_TAG}\]" "actions/$action/CHANGELOG.md"; then
              FILTERED_ACTIONS="$FILTERED_ACTIONS $action"
            fi
          done
          echo "Filtered actions: $FILTERED_ACTIONS"
          echo "filtered_actions=$(echo $FILTERED_ACTIONS | jq -R -s -c 'split(\" \")')" >> $GITHUB_EN

  release:
    needs: filter-changed-actions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        actions: ${{ fromJson(needs.actions.outputs.filtered_actions) }}

    steps:
      - name: Extract changelog content
        id: extract-changelog
        run: |
          VERSION_TAG="echo ${{ github.ref }} | awk -F '/' '{print $NF}'"
          RELEASE_CONTENT=$(awk "/^## \[${VERSION_TAG}\]/ {flag=1; next} /^## / {flag=0} flag {print}" actions/${{ matrix.actions }}/CHANGELOG.md)
          echo "release_body=${RELEASE_CONTENT}" >> $GITHUB_ENV
          echo "release_name=${VERSION_TAG}" >> $GITHUB_ENV

      - name: Release ${{ matrix.actions }} version ${{ github.ref }}
        uses: ./actions/release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ matrix.actions }} ${{ env.release_name }} # Get the action and the tag name
          release_body: ${{ env.release_body }} # Get the changelog

