name: Test and Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read



jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        actions: ['github-release']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: arduino/setup-task@v2

      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1

      - name: Lint action ${{ matrix.actions }}
        run: task ${{ matrix.actions}}:lint

      - name: Test action ${{ matrix.actions }}
        run: task ${{ matrix.actions}}:test
