name: Test and Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read



jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        actions: ['']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: arduino/setup-task@v2

      - name: Lint action ${{ matrix.actions }}
        uses: golangci/golangci-lint-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: true
          working-directory: ./actions/${{ matrix.actions }}
          args: --config=${{ github.workspace }}/.golangci.yml

      - name: Test action ${{ matrix.actions }}
        run: task ${{ matrix.actions}}:test
